name       : tea
version    : 0.7.0
release    : 3
source     :
    - https://gitea.com/gitea/tea/archive/v0.7.0.tar.gz : 0d65b49410321535ffcbba7795651cbef81911552f12f7617c9cf77a9d7d5da9
homepage   : https://gitea.com/gitea/tea
license    : MIT
component  : system.utils
summary    : A command line tool to interact with Gitea servers
description: |
    Tea is a command line tool for interacting on one or more Gitea instances. It uses the Gitea SDK and interacts with the Gitea API.
builddeps  :
    - golang
build      : |
    %make TEA_VERSION=v%version%
install    : |
    install -Dm00755 tea $installdir/usr/bin/tea
    install -Dm00644 $pkgfiles/tea.bash $installdir/usr/share/bash-completion/completions/tea
    install -Dm00644 $pkgfiles/tea.zsh $installdir/usr/share/zsh/site-functions/_tea
