name       : tea
version    : 0.6.0
release    : 1
source     :
    - https://gitea.com/gitea/tea/archive/v0.6.0.tar.gz : 048e6235885bec6a45ca22fba95b163d1d64b683f2f41c9c6339aacc7541f869
homepage   : https://gitea.com/gitea/tea
license    : MIT
component  : system.utils
summary    : A command line tool to interact with Gitea servers
description: |
    Tea is a command line tool for interacting on one or more Gitea instances. It uses the Gitea SDK and interacts with the Gitea API.
builddeps  :
    - golang
build      : |
    %make TEA_VERSION=v%version%
install    : |
    install -Dm00755 tea $installdir/usr/bin/tea
    install -Dm00644 $pkgfiles/tea.bash $installdir/usr/share/bash-completion/completions/tea
    install -Dm00644 $pkgfiles/tea.zsh $installdir/usr/share/zsh/site-functions/_tea
